# SonarQube Cloud (sonarcloud.io). Crear la org y el SONAR_TOKEN como secret del repo.
sonar.projectKey=gcamargot_devsu-challenge
sonar.organization=gcamargot

sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/*.test.js
sonar.exclusions=app/node_modules/**,app/coverage/**

sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
